[package]
name = "test-arch-menu"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.20.1"
crossterm = "0.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"


